[rust]
backtrace = false

[target.x86_64-unknown-redox]
cc = "x86_64-unknown-redox-gcc"
cxx = "x86_64-unknown-redox-g++"
llvm-config = "./llvm-config"

[build]
host = ["x86_64-unknown-redox"]
target = ["x86_64-unknown-redox"]
